"""Create Game Model

Revision ID: 10445ce78ef5
Revises: faebd12f9523
Create Date: 2024-01-11 15:52:24.991729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10445ce78ef5'
down_revision = 'faebd12f9523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
